namespace ExcelQueryCLI.Static;

public enum CompareOperator
{
  EQUALS,
  NOT_EQUALS,
  GREATER_THAN,
  LESS_THAN,
  GREATER_THAN_OR_EQUAL,
  LESS_THAN_OR_EQUAL,
  CONTAINS,
  NOT_CONTAINS,
  STARTS_WITH,
  ENDS_WITH,
  BETWEEN,
  NOT_BETWEEN,
  IS_NULL_OR_BLANK,
  IS_NOT_NULL_OR_BLANK
}